### ISSUE TITLE
[bug] Video player

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#68]
The video player needs some modifications.
It doesn't display anime name or episode name when you pause the anime
Also when you finish an episode and wait for the next episode to play, the next episode starts where the previous episode ended like the end of the episode and not the beginning and it's start to play in sub even if the first episode you watched in dub.
Also a suggestion to the video player, i suggest you add the anime name like that colored name when you open anime info and episode number or name to display on the video player when the video is paused.

**Comment by ErickLimaS** [comment]
As i said on other issue, Dub options is broken on some components, and i'll fix it some time. 

And the episode starting from where the previous episode ended, its really a bug and its also to be fix.

Regarding the episode name on the player... it doesnt have a option to do it. I didnt created it myself, i used an external library just for that. But im already looking for other options. Like, the Quality Selector on Settings Panel is still on Beta because of this library.

Again, thanks for the Issue, man, some things just happen when i make the deploy...

**Comment by Drac1652** [comment]
Okay man we are in this together
